name: Build Java

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Executar build.bat
        shell: cmd
        run: set CI=true && build.bat

      - name: Enviar executável
        uses: actions/upload-artifact@v4
        with:
          name: Stella-exe
          path: dist/**/*
          if-no-files-found: error