name: Build Java

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Executar build.bat
        run: cmd /c build.bat
        shell: cmd

      - name: Enviar JAR
        uses: actions/upload-artifact@v4
        with:
          name: Stella
          path: "*.jar"